name: Manually Deploy to heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: '94d5187b-5de3-4327-9598-888083318c19'
          heroku_app_name: 'mengsjhdkjdhksgoks'
          heroku_email: 'jourdyn16@needlegqu.com'
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
